name: sketcher
description: Sketch your ideas to life with the sketcher package. Provides the handwriting widget that allows to import\export content to SVG.
version: 2.0.0
homepage: https://github.com/glynskyi/sketcher

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  ktx: ^1.1.6
  path_parsing: ^1.0.0
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter: