name: sketcher
description: Sketch your ideas to life with the sketcher package. Provides the handwriting widget that allows to import\export content to SVG.
version: 1.1.12
homepage: https://github.com/glynskyi/sketcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0-nullsafety.0
  ktx: ^1.1.6
  path_parsing: ^0.2.0-nullsafety.0
  xml: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter: